version: '3'
services:
  redis:
    image: "redis"
    ports:
    - "6379:6379/tcp"
  mssql:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
    - "1433:1433/tcp"